var mymap = L.map('mapid').setView([53.505, -4], 6);  

L.tileLayer('https://api.mapbox.com/styles/v1/{id}/tiles/{z}/{x}/{y}?access_token=pk.eyJ1IjoiY2FsbHVtbHRob21zb24iLCJhIjoiY2o4b3E5ZHBkMDZvNjMzcWNiYTBhNXhuMSJ9.u8ObZkzwPyKqicBj7rLF2g', {
    attribution: 'Map data &copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors, Imagery © <a href="https://www.mapbox.com/">Mapbox</a>',
    maxZoom: 18,
    id: 'mapbox/light-v10',
    tileSize: 512,
    zoomOffset: -1,
    accessToken: 'your.mapbox.access.token'
}).addTo(mymap);

var marker1 = L.marker([51.465925, -2.619173]).addTo(mymap);
marker1.bindPopup("<strong><a href='http://www.cdd.ac.uk/' target='_blank' rel='noopener noreferrer'>Conservatoire for Dance and Drama (Bristol Old Vic Theatre School)</a></strong><br><br>In 2018-19, <strong>80.4%</strong> of British students at the CDD's six schools across England were from state schools or colleges.<br><br>In the same year, it received <strong>£4.3 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,100 per student</strong>.");
var marker2 = L.marker([51.522317, -0.108705]).addTo(mymap);
marker2.bindPopup("<strong><a href='http://www.cdd.ac.uk/' target='_blank' rel='noopener noreferrer'>Conservatoire for Dance and Drama (Central School of Ballet)</a></strong><br><br>In 2018-19, <strong>81.4%</strong> of British students at the CDD's six schools across England were from state schools or colleges.<br><br>In the same year, it received <strong>£4.3 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,100 per student</strong>.");
var marker3 = L.marker([51.52727, -0.128599]).addTo(mymap);
marker3.bindPopup("<strong><a href='http://www.cdd.ac.uk/' target='_blank' rel='noopener noreferrer'>Conservatoire for Dance and Drama (London Contemporary Dance School)</a></strong><br><br>In 2018-19, <strong>82.4%</strong> of British students at the CDD's six schools across England were from state schools or colleges.<br><br>In the same year, it received <strong>£4.3 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,100 per student</strong>.");
var marker4 = L.marker([51.527295, -0.082419]).addTo(mymap);
marker4.bindPopup("<strong><a href='http://www.cdd.ac.uk/' target='_blank' rel='noopener noreferrer'>Conservatoire for Dance and Drama (National Centre for Circus Arts)</a></strong><br><br>In 2018-19, <strong>83.4%</strong> of British students at the CDD's six schools across England were from state schools or colleges.<br><br>In the same year, it received <strong>£4.3 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,100 per student</strong>.");
var marker5 = L.marker([53.813069, -1.533471]).addTo(mymap);
marker5.bindPopup("<strong><a href='http://www.cdd.ac.uk/' target='_blank' rel='noopener noreferrer'>Conservatoire for Dance and Drama (Northern School of Contemporary Dance)</a></strong><br><br>In 2018-19, <strong>84.4%</strong> of British students at the CDD's six schools across England were from state schools or colleges.<br><br>In the same year, it received <strong>£4.3 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,100 per student</strong>.");
var marker6 = L.marker([51.461274, -0.321879]).addTo(mymap);
marker6.bindPopup("<strong><a href='http://www.cdd.ac.uk/' target='_blank' rel='noopener noreferrer'>Conservatoire for Dance and Drama (Rambert School of Ballet and Contemporary Dance)</a></strong><br><br>In 2018-19, <strong>85.4%</strong> of British students at the CDD's six schools across England were from state schools or colleges.<br><br>In the same year, it received <strong>£4.3 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,100 per student</strong>.");
var marker7 = L.marker([51.483587, -0.007198]).addTo(mymap);
marker7.bindPopup("<strong><a href='https://www.trinitylaban.ac.uk/' target='_blank' rel='noopener noreferrer'>Trinity Laban Conservatoire of Music and Dance</a></strong><br><br>In 2018-19, <strong>87.6%</strong> of British students at Trinity were from state schools or colleges.<br><br>In the same year, it received <strong>£4.2 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,801 per student</strong>.");
var marker8 = L.marker([51.519517, -0.092374]).addTo(mymap);
marker8.bindPopup("<strong><a href='https://www.gsmd.ac.uk/' target='_blank' rel='noopener noreferrer'>Guildhall School of Music and Drama</a></strong><br><br>In 2018-19, <strong>65.9%</strong> of British students at the Guildhall were from state schools or colleges.<br><br>In the same year, it received <strong>£4 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,902 per student</strong>.");
var marker9 = L.marker([51.544325, -0.174205]).addTo(mymap);
marker9.bindPopup("<strong><a href='https://www.cssd.ac.uk/' target='_blank' rel='noopener noreferrer'>The Royal Central School of Speech and Drama</a></strong><br><br>In 2018-19, <strong>88.4%</strong> of British students at Central School were from state schools or colleges.<br><br>In the same year, it received <strong>£4 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£3,980 per student</strong>.");
var marker10 = L.marker([51.60481, -0.638465]).addTo(mymap);
marker10.bindPopup("<strong><a href='https://nfts.co.uk/' target='_blank' rel='noopener noreferrer'>The National Film and Television School</a></strong><br><br>There is <strong>no available data</strong> on the proportion of British students at NFTS that were from state schools or colleges in 2018-19.<br><br>In the same year, it received <strong>£1.2 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£4,142 per student</strong>.");
var marker11 = L.marker([51.485644, -3.183856]).addTo(mymap);
marker11.bindPopup("<strong><a href='https://www.rwcmd.ac.uk/' target='_blank' rel='noopener noreferrer'>Royal Welsh College of Music and Drama</a></strong><br><br>There is <strong>no available data</strong> on the proportion of British students at the RWCMD that were from state schools or colleges in 2018-19.<br><br>In the same year, it received <strong>£3.5 million</strong> in specialist institution funding from the Higher Education Funding Council for Wales, equivalent to <strong>£4,443 per student</strong>.");
var marker12 = L.marker([51.523497, -0.1517]).addTo(mymap);
marker12.bindPopup("<strong><a href='https://www.ram.ac.uk/' target='_blank' rel='noopener noreferrer'>Royal Academy of Music</a></strong><br><br>In 2018-19, <strong>41.8%</strong> of British students at the RAM were from state schools or colleges.<br><br>In the same year, it received <strong>£3.8 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£4,479 per student</strong>.");
var marker13 = L.marker([53.468557, -2.236963]).addTo(mymap);
marker13.bindPopup("<strong><a href='https://www.rncm.ac.uk/' target='_blank' rel='noopener noreferrer'>Royal Northern College of Music</a></strong><br><br>In 2018-19, <strong>73.6%</strong> of British students at the RNCM were from state schools or colleges.<br><br>In the same year, it received <strong>£4 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£4,651 per student</strong>.");
var marker14 = L.marker([51.499279, -0.176913]).addTo(mymap);
marker14.bindPopup("<strong><a href='https://www.rcm.ac.uk/' target='_blank' rel='noopener noreferrer'>Royal College of Music</a></strong><br><br>In 2018-19, <strong>39.7%</strong> of British students at the RCM were from state schools or colleges.<br><br>In the same year, it received <strong>£4 million</strong> in specialist institution funding from the Office for Students, equivalent to <strong>£5,063 per student</strong>.");
var marker15 = L.marker([55.865813, -4.257595]).addTo(mymap);
marker15.bindPopup("<strong><a href='https://www.rcs.ac.uk/' target='_blank' rel='noopener noreferrer'>Royal Conservatoire of Scotland</a></strong><br><br>In 2018-19, <strong>84.4%</strong> of British students at the RCS were from state schools or colleges.<br><br>In the same year, it received <strong>£5.9 million</strong> in specialist institution funding from the Scottish Funding Council, equivalent to <strong>£5,018 per student</strong>.");
